// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUfvV9Jm4PEm9Pg9FT3x8B7eb72fSPAMo',
    appId: '1:744898539698:web:68dcbdadb44fa2cb0519ab',
    messagingSenderId: '744898539698',
    projectId: 'serendip-fd062',
    authDomain: 'serendip-fd062.firebaseapp.com',
    storageBucket: 'serendip-fd062.appspot.com',
    measurementId: 'G-MPZ7T02MKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcI23pZ3H4I1aYOZzUdsnX8TKNreTIthQ',
    appId: '1:744898539698:android:64f7010021da48400519ab',
    messagingSenderId: '744898539698',
    projectId: 'serendip-fd062',
    storageBucket: 'serendip-fd062.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx0WS04RbtMReNBLHnP_J5Duh5G4kxsWs',
    appId: '1:744898539698:ios:6ec495521b7cdc210519ab',
    messagingSenderId: '744898539698',
    projectId: 'serendip-fd062',
    storageBucket: 'serendip-fd062.appspot.com',
    androidClientId: '744898539698-66st3j8nccjji3igghu21dkf4m5538fg.apps.googleusercontent.com',
    iosClientId: '744898539698-ili1iens183m7auqes45r7fi1r9o5noh.apps.googleusercontent.com',
    iosBundleId: 'com.example.serendip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx0WS04RbtMReNBLHnP_J5Duh5G4kxsWs',
    appId: '1:744898539698:ios:6ec495521b7cdc210519ab',
    messagingSenderId: '744898539698',
    projectId: 'serendip-fd062',
    storageBucket: 'serendip-fd062.appspot.com',
    androidClientId: '744898539698-66st3j8nccjji3igghu21dkf4m5538fg.apps.googleusercontent.com',
    iosClientId: '744898539698-ili1iens183m7auqes45r7fi1r9o5noh.apps.googleusercontent.com',
    iosBundleId: 'com.example.serendip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUfvV9Jm4PEm9Pg9FT3x8B7eb72fSPAMo',
    appId: '1:744898539698:web:c27331e64e5e92720519ab',
    messagingSenderId: '744898539698',
    projectId: 'serendip-fd062',
    authDomain: 'serendip-fd062.firebaseapp.com',
    storageBucket: 'serendip-fd062.appspot.com',
    measurementId: 'G-3T5GZS4KEM',
  );
}
